-- 정책 마스터 테이블
-- 행안부·복지부·청년정책 등 외부 API에서 수집한 정책을 정규화하여 저장
CREATE TABLE POLICY_MASTER (
  ID              VARCHAR2(40)  PRIMARY KEY,
  TENANT_ID       VARCHAR2(20)  DEFAULT 'COMMON' NOT NULL,
  SOURCE          VARCHAR2(20)  NOT NULL,
  SOURCE_ID       VARCHAR2(60)  NOT NULL,
  CATEGORY        VARCHAR2(40),
  LIFECYCLE       VARCHAR2(200),
  TITLE           VARCHAR2(500) NOT NULL,
  ORG             VARCHAR2(200),
  DESCRIPTION     CLOB,
  AMOUNT_TEXT     VARCHAR2(500),
  TARGET_TEXT     VARCHAR2(2000),
  TARGET_AGE_MIN  NUMBER(3),
  TARGET_AGE_MAX  NUMBER(3),
  REGION          VARCHAR2(100),
  APPLY_START     DATE,
  APPLY_END       DATE,
  APPLY_URL       VARCHAR2(1000),
  TAGS            VARCHAR2(1000),
  STATUS          VARCHAR2(20)  DEFAULT 'ACTIVE',
  LAST_SYNC       DATE,
  CREATED_AT      DATE          DEFAULT SYSDATE,
  UPDATED_AT      DATE          DEFAULT SYSDATE,
  CONSTRAINT UQ_POLICY_SOURCE UNIQUE (SOURCE, SOURCE_ID, TENANT_ID)
);

-- 인덱스
CREATE INDEX IDX_POLICY_TENANT_CAT ON POLICY_MASTER(TENANT_ID, CATEGORY);
CREATE INDEX IDX_POLICY_LIFECYCLE  ON POLICY_MASTER(LIFECYCLE);
CREATE INDEX IDX_POLICY_AGE        ON POLICY_MASTER(TARGET_AGE_MIN, TARGET_AGE_MAX);
CREATE INDEX IDX_POLICY_DEADLINE   ON POLICY_MASTER(APPLY_END);
CREATE INDEX IDX_POLICY_STATUS     ON POLICY_MASTER(STATUS);

-- 코멘트
COMMENT ON TABLE POLICY_MASTER IS '외부 공공API에서 수집·정규화한 정책 마스터';
COMMENT ON COLUMN POLICY_MASTER.SOURCE IS 'gov24, youth, work24, welfare, local';
COMMENT ON COLUMN POLICY_MASTER.LIFECYCLE IS '쉼표 구분: youth,marry,birth,care,senior';
COMMENT ON COLUMN POLICY_MASTER.STATUS IS 'ACTIVE, HIDDEN, FILTERED';